lib/instagram_web/router.ex
defmodule InstagramWeb.Router do
  use InstagramWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug InstagramWeb.Plugs.SetUser
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InstagramWeb do
    pipe_through :browser

    get "/", AlbumController, :index
    get "/dashboard/form", DashboardController , :index
    get "/edit/:id" , AlbumController,:edit
    put "/edit/update/:id",AlbumController,:update
    post "/dashboard/send" , DashboardController , :create
    delete "/delete/:id" , AlbumController,:delete
    get "view/:id" , AlbumController , :show
  end


  scope "/auth", InstagramWeb do
    pipe_through :browser
    pipe_through :api
    get "/register" ,AuthController , :register
    post "/registering",AuthController,:registering
    get "/login" , AuthController , :login
    post "login/" , AuthController,:callback
    get "logout" , AuthController ,:logout

    get "/:provider" , AuthController , :request_google
    get "/:provider/callback" , AuthController , :callback_google
  end


  # Other scopes may use custom stacks.
  scope "/api", InstagramWeb do
    pipe_through :api

    get "/albums" , AlbumApiController , :index
    get "/albums/:id" , AlbumApiController , :show
    post "/albums/create" , AlbumApiController , :create
    delete "/albums/delete" ,AlbumApiController , :delete
  end
#/:title/:body/:image
  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  # if Mix.env() in [:dev, :test] do
  #   import Phoenix.LiveDashboard.Router

  #   scope "/" do
  #     pipe_through :browser
  #     live_dashboard "/dashboard", metrics: InstagramWeb.Telemetry
  #   end
  # end
end

lib/instagram_web/controllers/album_controller.ex
defmodule InstagramWeb.AlbumController do
  use InstagramWeb , :controller
  alias Instagram.Article
  alias Instagram.Repo
  alias Instagram.Auth

  plug :check_topic_owner when action in [:update,:edit,:delete]
  def index(conn, _params) do
    IO.inspect(conn)
    IO.inspect("++++++++++++++++++++++++")
    posts = Repo.all(Article)
    IO.inspect(posts)
    render(conn, "index.html",posts: posts,repo: Repo,auth: Auth)
  end

  def edit(conn,%{"id" => article_id} = params) do
    IO.inspect(conn)
    IO.inspect("++++++++++++++++++++++++")

    old_post = Repo.get(Article,article_id)
    IO.inspect(old_post)

    changeset = Article.changeset(old_post)
    render conn,"edit.html",changeset: changeset , post: old_post
  end

  def update(conn,%{"article" => article} = params) do
    %{"id" => article_id} = params
    old_post = Repo.get(Article,article_id)
    changeset = Article.changeset(old_post,article)

    case Repo.update(changeset) do
      {:ok,_post} ->
        conn
        |> put_flash(:info,"Article Edited!")
        |> redirect(to: Routes.album_path(conn,:edit,old_post))
    end
  end

  def delete(conn,%{"id" => article_id} = params) do
    Repo.get(Article,article_id)
    |> Repo.delete!
    redirect(conn,to: Routes.album_path(conn,:index))
  end

  def show(conn,%{"id" => article_id}) do
    article = Repo.get(Article,article_id)
    render conn,"view.html" , article: article
  end

  def check_topic_owner(conn,params) do
    if conn.assigns.user do
      %{params: %{"id" => article_id}} = conn
      if Repo.get(Article,article_id).auth_id == conn.assigns.user.id do
        conn
      else
        conn
        |> put_flash(:error,"404 Not Found! :(")
        |> redirect(to: Routes.album_path(conn,:index))
        |> halt()
      end
    else
      conn
      |> put_flash(:error,"404 Not Found! :(")
      |> redirect(to: Routes.album_path(conn,:index))
      |> halt()
    end
end

end

lib/instagram_web/views/album_view.ex
defmodule InstagramWeb.AlbumView do
  use InstagramWeb, :view
end

lib/instagram_web/templates/album/edit.html.eex
<%= form_for @changeset,Routes.album_path(@conn,:update,@post), [multipart: true],fn f -> %>
    <div class="form-group">
    <%= text_input f, :title , class: "form-control mt-4" , placeholder: "Enter title" %>
    <%= text_input f, :body , class: "form-control mt-4" , placeholder: "Enter article" %>
    <% file_input f, :image , class: "form-control mt-4" %>
    <%= submit "Submit", class: "btn btn-primary mt-5" %>
    </div>
<% end %>

lib/instagram_web/templates/album/index.html.eex
   <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Welcome to Album</h1>
          <p class="lead text-muted">Welcome to Album website. you can share images and discuss about it with others</p>
          <p>
            <%= link "Create a post" ,to: Routes.dashboard_path(@conn,:index), class: "btn btn-primary my-2" %>
            <%= if @conn.assigns.user do %>
              <%= link "LogOut" , class: "btn btn-danger", to: Routes.auth_path(@conn,:logout) %>
            <% else %>
            <%= link "Login" , class: "btn btn-secondary", to: Routes.auth_path(@conn,:login) %>
            <% end %>
          </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">

          <div class="row">
          <%= for post <- @posts do %>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="<%= Routes.static_path(@conn, "/images/#{post.image}") %>" alt="Card image cap">
                <div class="card-body">
                  <p class="card-text"><%= post.body%></p>
                  <div class="d-flex justify-content-between align-items-center">

                    <div class="btn-group">
                      <%= if @conn.assigns.user do %>
                        <%= if @conn.assigns.user.id == post.auth_id do%>
                        <%= link "Edit" , class: "btn btn-sm btn-outline-secondary" , to: Routes.album_path(@conn,:edit,post) %>
                        <%= link "Delete" , class: "btn btn-sm btn-outline-secondary" , to: Routes.album_path(@conn,:delete,post), method: :delete %>
                        <% end %>
                      <% end %>
                        <%= link "View" , class: "btn btn-sm btn-outline-secondary" , to: Routes.album_path(@conn,:show,post) %>
                    </div>
                    <small class="text-muted ml-2"><%= post.inserted_at %></small><br>
                    <small class="text-muted">Sent by <%= @repo.get(@auth,post.auth_id).fname %></small><br>
                  </div>
                </div>
              </div>
            </div>

          <% end %>
          </div>
        </div>
      </div>

lib/instagram_web/templates/album/view.html.eex
  <h1 class="display-4 mt-4">Comments with Socket </h1>
<div class= "d-flex flex-column justify-content-center mt-5">
<img width="500" height="200" src="<%= Routes.static_path(@conn, "/images/#{@article.image}")%>"/>
<br>

<%= @article.title %> <br>
<%= @article.body %><br>
</div>
<div class="mt-5">
<h5 class="lead">Send a Comment</h5>
<div class="form-group">
    <input id="form-comment" class="form-control w-50" placeholder = "Comment">
    <button id="btn" class="btn btn-success mt-2">Send Comment</button>
</div>

<ul class="list-group list-unstyled">


<ul>
</div>

<script>
    document.addEventListener("DOMContentLoaded", function(){
      window.createSocket(<%= @article.id %>)
    })

</script>